Neos:
  Fusion:
    defaultContext:
      NotFound.Context: MOC\NotFound\Fusion\Eel\Helper\ContextHelper
      NotFound.LocaleHelper: MOC\NotFound\Fusion\Eel\Helper\LocaleHelper
  Neos:
    fusion:
      autoInclude:
        MOC.NotFound: true
MOC:
  NotFound:
    uriPathSegment: 404
    languageDimensionName: language